// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Forward = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Forward, 60);
    lv_obj_set_height(ui_Forward, 60);
    lv_obj_set_x(ui_Forward, -120);
    lv_obj_set_y(ui_Forward, -80);
    lv_obj_set_align(ui_Forward, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Forward, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Forward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Left = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Left, 60);
    lv_obj_set_height(ui_Left, 60);
    lv_obj_set_x(ui_Left, -200);
    lv_obj_set_y(ui_Left, 0);
    lv_obj_set_align(ui_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Left, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Right = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Right, 60);
    lv_obj_set_height(ui_Right, 60);
    lv_obj_set_x(ui_Right, -40);
    lv_obj_set_y(ui_Right, 0);
    lv_obj_set_align(ui_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Right, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_back = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_back, 60);
    lv_obj_set_height(ui_back, 60);
    lv_obj_set_x(ui_back, -120);
    lv_obj_set_y(ui_back, 80);
    lv_obj_set_align(ui_back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_point = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_point, 100);
    lv_obj_set_height(ui_point, 50);
    lv_obj_set_x(ui_point, 120);
    lv_obj_set_y(ui_point, -80);
    lv_obj_set_align(ui_point, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_point, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_point, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_continuous = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_continuous, 100);
    lv_obj_set_height(ui_continuous, 50);
    lv_obj_set_x(ui_continuous, 120);
    lv_obj_set_y(ui_continuous, 0);
    lv_obj_set_align(ui_continuous, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_continuous, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_continuous, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MotorStop = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_MotorStop, 100);
    lv_obj_set_height(ui_MotorStop, 50);
    lv_obj_set_x(ui_MotorStop, 120);
    lv_obj_set_y(ui_MotorStop, 80);
    lv_obj_set_align(ui_MotorStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MotorStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -120);
    lv_obj_set_y(ui_Label1, -35);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Forward");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -150);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Left");

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -95);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Right");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -120);
    lv_obj_set_y(ui_Label4, 35);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Back");

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 123);
    lv_obj_set_y(ui_Label5, -40);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "point_mode");

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 123);
    lv_obj_set_y(ui_Label6, 40);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "continuous_mode");

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 123);
    lv_obj_set_y(ui_Label7, 120);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Motor_Stop");

}
